dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: zookeeper://47.93.9.181:2181
    # 读者请换成自己的zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000

server:
  port: 8062

  redis:
    database: 0
    host: 47.93.9.181
    password:
    port: 6370
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000

